/**
 * Mock 数据 — 模拟生活/工作类需求卡片
 * 覆盖家居、育儿、职场、消费、健康等领域
 */

import { DemandCard, DomainStats, TrendPoint } from "./types";

/** 生成 Mock 需求卡片列表 */
export const mockDemands: DemandCard[] = [
  {
    id: "dc-001",
    domain: "家居收纳",
    sub_domain: "厨房整理",
    persona: "家庭主妇",
    pain_point: "厨房台面永远乱糟糟，调料瓶、锅具、小家电堆满，每次做饭都找不到东西",
    desired_outcome: "一套不占台面、拿取方便、又能防油烟的厨房收纳方案",
    current_alternative: "各种收纳盒混用，没有统一标准",
    evidence_type: "complaint",
    intensity: 8,
    mentioned_tools: ["宜家收纳盒", "洞洞板", "磁吸刀架"],
    source: "xiaohongshu",
    url: "https://xiaohongshu.com/explore/xxx",
    published_at: "2026-07-20T08:30:00Z",
    overall_score: 85.2,
    frequency_score: 4.0,
    recency_score: 0.9,
    market_score: 0.85,
    competition_score: 0.5,
  },
  {
    id: "dc-002",
    domain: "育儿教育",
    sub_domain: "作业辅导",
    persona: "小学生家长",
    pain_point: "每天辅导孩子数学作业到崩溃，讲三遍还是不懂，自己情绪失控吼孩子",
    desired_outcome: "能让孩子自主完成作业、家长不用盯的工具或方法",
    current_alternative: "自己硬教 + 偶尔请家教",
    evidence_type: "help_seeking",
    intensity: 9,
    mentioned_tools: ["作业帮", "小猿搜题", "学而思"],
    source: "zhihu",
    url: "https://zhihu.com/question/xxx",
    published_at: "2026-07-19T14:20:00Z",
    overall_score: 88.5,
    frequency_score: 4.2,
    recency_score: 0.88,
    market_score: 0.9,
    competition_score: 0.6,
  },
  {
    id: "dc-003",
    domain: "职场效率",
    sub_domain: "报表制作",
    persona: "行政文员",
    pain_point: "每周要做5张Excel报表，手动复制粘贴数据，公式学不会，加班两小时才能搞定",
    desired_outcome: "不用学复杂公式就能自动生成报表的工具，最好像填表一样简单",
    current_alternative: "纯手动 Excel 操作",
    evidence_type: "help_seeking",
    intensity: 8,
    mentioned_tools: ["Excel", "WPS", "钉钉报表"],
    source: "zhihu",
    url: "https://zhihu.com/question/yyy",
    published_at: "2026-07-18T09:15:00Z",
    overall_score: 82.3,
    frequency_score: 3.8,
    recency_score: 0.85,
    market_score: 0.88,
    competition_score: 0.55,
  },
  {
    id: "dc-004",
    domain: "消费决策",
    sub_domain: "家电选购",
    persona: "租房青年",
    pain_point: "想买个扫地机器人但品牌太多，评论好坏参半，花了三天研究还是选不出来",
    desired_outcome: "能根据自己实际需求和预算直接推荐合适产品的工具，而不是看一堆软文",
    current_alternative: "看小红书测评 + 知乎对比帖",
    evidence_type: "comparison",
    intensity: 7,
    mentioned_tools: ["小米", "石头", "追觅", "科沃斯"],
    source: "xiaohongshu",
    url: "https://xiaohongshu.com/explore/aaa",
    published_at: "2026-07-17T16:45:00Z",
    overall_score: 76.8,
    frequency_score: 3.5,
    recency_score: 0.82,
    market_score: 0.8,
    competition_score: 0.7,
  },
  {
    id: "dc-005",
    domain: "健康管理",
    sub_domain: "久坐健身",
    persona: "上班族",
    pain_point: "每天坐办公室8小时腰酸背痛，办了健身卡却从不去，在家也不知道怎么锻炼",
    desired_outcome: "不用去健身房、每天15分钟在家就能做的简单锻炼方案，最好能提醒打卡",
    current_alternative: "买了瑜伽垫积灰 + 关注健身博主但从不跟练",
    evidence_type: "complaint",
    intensity: 7,
    mentioned_tools: ["Keep", "B站健身视频", "健身卡"],
    source: "weibo",
    url: "https://weibo.com/xxx",
    published_at: "2026-07-16T11:00:00Z",
    overall_score: 74.2,
    frequency_score: 3.2,
    recency_score: 0.78,
    market_score: 0.85,
    competition_score: 0.65,
  },
  {
    id: "dc-006",
    domain: "家居收纳",
    sub_domain: "衣柜整理",
    persona: "都市女性",
    pain_point: "衣服多到衣柜塞不下，每次换季翻箱倒柜，找不到想穿的那件，买了收纳箱还是乱",
    desired_outcome: "能根据衣柜尺寸和衣服数量给出个性化收纳方案的工具或服务",
    current_alternative: "各种收纳箱 + 真空压缩袋",
    evidence_type: "complaint",
    intensity: 7,
    mentioned_tools: ["宜家衣架", "收纳箱", "真空压缩袋"],
    source: "xiaohongshu",
    url: "https://xiaohongshu.com/explore/bbb",
    published_at: "2026-07-15T13:30:00Z",
    overall_score: 71.5,
    frequency_score: 3.0,
    recency_score: 0.75,
    market_score: 0.8,
    competition_score: 0.6,
  },
  {
    id: "dc-007",
    domain: "职场效率",
    sub_domain: "会议记录",
    persona: "项目经理",
    pain_point: "每天开4-5个会，会议记录整理耗时太长，重点经常遗漏，纪要分发也不及时",
    desired_outcome: "能自动录音转文字、提取重点、生成结构化纪要的工具",
    current_alternative: "手动记笔记 + 会后整理 Word",
    evidence_type: "help_seeking",
    intensity: 8,
    mentioned_tools: ["飞书妙记", "讯飞听见", "Notion"],
    source: "zhihu",
    url: "https://zhihu.com/question/ccc",
    published_at: "2026-07-14T10:00:00Z",
    overall_score: 79.8,
    frequency_score: 3.6,
    recency_score: 0.8,
    market_score: 0.82,
    competition_score: 0.55,
  },
  {
    id: "dc-008",
    domain: "消费决策",
    sub_domain: "母婴用品",
    persona: "新手妈妈",
    pain_point: "婴儿用品种类太多，不知道哪些真正需要哪些是智商税，花了很多冤枉钱",
    desired_outcome: "能根据宝宝月龄推荐真正必需品的清单，避免盲目消费",
    current_alternative: "看各种育儿博主推荐 + 群里问其他妈妈",
    evidence_type: "comparison",
    intensity: 7,
    mentioned_tools: ["奶瓶", "吸奶器", "婴儿车", "安抚奶嘴"],
    source: "xiaohongshu",
    url: "https://xiaohongshu.com/explore/ddd",
    published_at: "2026-07-13T15:20:00Z",
    overall_score: 73.0,
    frequency_score: 3.1,
    recency_score: 0.72,
    market_score: 0.78,
    competition_score: 0.68,
  },
  {
    id: "dc-009",
    domain: "财务管理",
    sub_domain: "家庭记账",
    persona: "家庭主妇",
    pain_point: "家庭开销糊涂账，每月不知道钱花哪了，用记账App坚持不了几天就放弃",
    desired_outcome: "能自动归类消费、不用手动记的记账方式，月底自动出报表",
    current_alternative: "微信账单截图 + 偶尔手动记账",
    evidence_type: "complaint",
    intensity: 8,
    mentioned_tools: ["随手记", "鲨鱼记账", "微信账单"],
    source: "zhihu",
    url: "https://zhihu.com/question/eee",
    published_at: "2026-07-12T09:00:00Z",
    overall_score: 80.6,
    frequency_score: 3.7,
    recency_score: 0.82,
    market_score: 0.85,
    competition_score: 0.5,
  },
  {
    id: "dc-010",
    domain: "育儿教育",
    sub_domain: "英语启蒙",
    persona: "幼儿家长",
    pain_point: "想给孩子英语启蒙但自己口语不好，报班太贵一年两万，不知道在家怎么教",
    desired_outcome: "低成本、家长能陪孩子一起学的英语启蒙方案",
    current_alternative: "买了点读笔 + 绘本，但使用频率低",
    evidence_type: "help_seeking",
    intensity: 7,
    mentioned_tools: ["点读笔", "叽里呱啦", "伴鱼绘本"],
    source: "xiaohongshu",
    url: "https://xiaohongshu.com/explore/fff",
    published_at: "2026-07-11T17:30:00Z",
    overall_score: 75.3,
    frequency_score: 3.3,
    recency_score: 0.7,
    market_score: 0.82,
    competition_score: 0.6,
  },
  {
    id: "dc-011",
    domain: "职场效率",
    sub_domain: "时间管理",
    persona: "自由职业者",
    pain_point: "在家办公效率低，经常被手机和家务打断，一天下来发现没做什么事",
    desired_outcome: "能强制专注、减少手机干扰的时间管理工具，最好有社交监督机制",
    current_alternative: "番茄钟App + 待办清单",
    evidence_type: "complaint",
    intensity: 6,
    mentioned_tools: ["番茄Todo", "Forest", "滴答清单"],
    source: "weibo",
    url: "https://weibo.com/ggg",
    published_at: "2026-07-10T08:00:00Z",
    overall_score: 68.4,
    frequency_score: 2.8,
    recency_score: 0.65,
    market_score: 0.75,
    competition_score: 0.7,
  },
  {
    id: "dc-012",
    domain: "健康管理",
    sub_domain: "饮食营养",
    persona: "上班族",
    pain_point: "每天中午不知道吃什么，外卖吃腻了又贵又不健康，带饭又没时间准备",
    desired_outcome: "能根据健康需求和口味偏好推荐每日餐食的方案，最好能一键下单食材",
    current_alternative: "随机点外卖 + 偶尔带饭",
    evidence_type: "help_seeking",
    intensity: 6,
    mentioned_tools: ["美团外卖", "饿了么", "下厨房"],
    source: "xiaohongshu",
    url: "https://xiaohongshu.com/explore/hhh",
    published_at: "2026-07-09T12:00:00Z",
    overall_score: 66.7,
    frequency_score: 2.6,
    recency_score: 0.6,
    market_score: 0.78,
    competition_score: 0.65,
  },
];

/** Mock 领域统计 */
export const mockDomainStats: DomainStats[] = [
  { domain: "家居收纳", count: 32, avg_intensity: 7.2 },
  { domain: "育儿教育", count: 28, avg_intensity: 7.8 },
  { domain: "职场效率", count: 25, avg_intensity: 7.0 },
  { domain: "消费决策", count: 22, avg_intensity: 6.5 },
  { domain: "健康管理", count: 18, avg_intensity: 6.3 },
  { domain: "财务管理", count: 12, avg_intensity: 7.5 },
];

/** Mock 趋势数据(最近 30 天) */
export function generateMockTrends(days: number = 30): TrendPoint[] {
  const points: TrendPoint[] = [];
  const now = new Date();
  for (let i = days - 1; i >= 0; i--) {
    const date = new Date(now);
    date.setDate(date.getDate() - i);
    // 模拟随机波动但有上升趋势
    const base = 3 + (days - i) * 0.15;
    const noise = Math.random() * 4;
    const count = Math.max(0, Math.round(base + noise));
    points.push({
      date: date.toISOString().slice(0, 10),
      count,
    });
  }
  return points;
}
